Repository hermeznetwork/hermez-node, pull requests merged in 2021-03, with the labels that each got.

#667 Document synchronizer, node and coordinator
  cli/node/README.md
  config/config.go
  coordinator/coordinator.go
  node/node.go
  synchronizer/synchronizer.go
Labels: documentation

#672 Add configuration option to choose recommended fee strategy, and add …
  api/api_test.go
  api/stateapiupdater/stateapiupdater.go
  cli/node/cfg.buidler.toml
  config/config.go
  node/node.go
Labels: node

#670 fix the invalid goarch build
  .gitignore
  .goreleaser.yml
Labels: bug

#677 Faster synchronization by fetching only block headers
  eth/ethereum.go
Labels: synchronizer

#636 instrumenting the application
  api/api.go
  api/handlers.go
  cli/node/cfg.buidler.toml
  coordinator/batch.go
  coordinator/pipeline.go
  metric/metric.go
  metric/request.go
  synchronizer/metrics.go
  synchronizer/synchronizer.go
  txselector/metrics.go
  txselector/txselector.go
Labels: enhancement, node

#683 Add package level documentation for db, historydb, l2db, api, apitype…
  api/api.go
  api/apitypes/apitypes.go
  api/stateapiupdater/stateapiupdater.go
  db/historydb/historydb.go
  db/l2db/l2db.go
  db/utils.go
Labels: documentation

#688 TxSel avoid L1CoordTx for L2Tx that have a L1UserTx in the frozen queue
  common/l1tx.go
  coordinator/pipeline.go
  db/historydb/historydb.go
  db/historydb/historydb_test.go
  test/zkproof/flows_test.go
  txselector/txselector.go
  txselector/txselector_test.go
Labels: txselector
